name: release

on:
  push:
    tags:
      - "*"

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Prevent from snapcraft fail
        run: |
          mkdir -p $HOME/.cache/snapcraft/download
          mkdir -p $HOME/.cache/snapcraft/stage-packages

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 'v2.10.2'
          args: release --clean --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-checksums: dist/lefthook_checksums.txt

      - name: Preserve artifacts permissions with tar
        run: tar -cvf dist.tar dist/
      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist.tar

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v8
        with:
          name: dist
      - run: tar -xvf dist.tar

      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - name: Prepare publish
        run: |
          cp -R packaging/registries/npm/lefthook-linux-arm64 packaging/registries/npm/lefthook-linux-loong64
          sed -i 's#arm64#loong64#g' packaging/registries/npm/lefthook-linux-loong64/package.json
          sed -i 's#ARM#LoongArch#g' packaging/registries/npm/lefthook-linux-loong64/package.json
          sed -i 's#"name": "@evilmartians/#"name": "@evilmartians-loong64/#g' packaging/registries/npm-bundled/package.json packaging/registries/npm-installer/package.json
          sed -i 's#github.com/evilmartians#github.com/loong64#g' packaging/registries/npm-bundled/package.json packaging/registries/npm-installer/package.json
          for d in packaging/registries/npm/*; do
            if [ -f "${d}/package.json" ]; then
              sed -i 's#"name": "lefthook#"name": "@loong64/lefthook#g' "${d}/package.json"
              sed -i 's#github.com/evilmartians#github.com/loong64#g' "${d}/package.json"
            fi
          done

      - uses: Raku/setup-raku@v1
      - name: Publish to NPM
        env:
          NPM_API_KEY: ${{ secrets.NPM_TOKEN }}
        run: |
          raku packaging/scripts/prepare.raku --target=npm
          raku packaging/scripts/publish.raku --target=npm
